[project]
name = "photo-server"
version = "1.0.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.118.0",
    "uvicorn>=0.34.2",
    "python-multipart>=0.0.20",
    "python-dotenv>=1.1.0",
    "starlette>=0.49.1",
    "itsdangerous>=2.2.0",
    "Jinja2>=3.1.6",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=4.5.0",
]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
